parameters:
    lch.seo.tools.class: Lch\SeoBundle\Service\Tools
    lch.seo.twig.extension.class: Lch\SeoBundle\Twig\SeoExtension
    lch.seo.doctrine.seo_listener.class: Lch\SeoBundle\Doctrine\SeoListener
    lch.seo.reflection.class_analyser.class: Lch\SeoBundle\Reflection\ClassAnalyzer

services:
    lch.seo.twig.extension:
        class: "%lch.seo.twig.extension.class%"
        arguments: ['@twig', '@lch.seo.tools']
        tags:
            - { name: twig.extension }
        lazy: true

    lch.seo.tools:
        class: "%lch.seo.tools.class%"
        arguments: ['@doctrine.orm.entity_manager', '@event_dispatcher', '@router', '%lch.seo.parameters%']
        lazy: true

    lch.seo.doctrine.listener:
        class: "%lch.seo.doctrine.seo_listener.class%"
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_subscriber }
        lazy: true

    lch.seo.reflection.class_analyzer:
        class:   "%lch.seo.reflection.class_analyser.class%"
