parameters:
  lch.seo.tools.class: Lch\SeoBundle\Service\Tools
  lch.seo.twig.extension.class: Lch\SeoBundle\Twig\SeoExtension

services:
  lch.seo.twig.extension:
    class: "%lch.seo.twig.extension.class%"
    arguments: ['@twig']
    tags:
      - { name: twig.extension }
    lazy: true

  lch.seo.tools:
    class: "%lch.seo.tools.class%"
    arguments: ['@doctrine.orm.entity_manager', '@event_dispatcher', '@router', '%lch.seo.sitemap%']
    lazy: true